from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from datetime import datetime
import os

def generate_report(data: dict) -> str:
    """Generate a PDF maintenance report."""
    os.makedirs("reports", exist_ok=True)
    filename = f"reports/maintenance_report_{data['asset_id']}_{datetime.now().strftime('%Y%m%d_%H%M')}.pdf"

    doc = SimpleDocTemplate(filename, pagesize=A4,
                             topMargin=2*cm, bottomMargin=2*cm,
                             leftMargin=2*cm, rightMargin=2*cm)

    styles = getSampleStyleSheet()
    story = []

    # Header
    header_style = ParagraphStyle("header", fontSize=18, fontName="Helvetica-Bold",
                                   textColor=colors.HexColor("#1a1a2e"), spaceAfter=6)
    sub_style = ParagraphStyle("sub", fontSize=11, textColor=colors.grey, spaceAfter=20)

    story.append(Paragraph("IRONMIND — Maintenance Decision Report", header_style))
    story.append(Paragraph(f"Generated: {datetime.now().strftime('%d %B %Y, %H:%M IST')}", sub_style))

    # Summary table
    severity_color = {
        "CRITICAL": colors.HexColor("#dc2626"),
        "HIGH": colors.HexColor("#ea580c"),
        "MEDIUM": colors.HexColor("#ca8a04"),
        "LOW": colors.HexColor("#16a34a"),
    }.get(data.get("risk_level", "HIGH"), colors.grey)

    summary_data = [
        ["Field", "Value"],
        ["Asset ID", data.get("asset_id", "N/A")],
        ["Fault Type", data.get("fault_type", "N/A")],
        ["Risk Level", data.get("risk_level", "N/A")],
        ["RUL (days)", str(data.get("rul_days", "N/A"))],
        ["Root Cause", data.get("root_cause", "N/A")],
        ["Report Date", datetime.now().strftime("%d/%m/%Y")],
    ]

    table = Table(summary_data, colWidths=[5*cm, 12*cm])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1a1a2e")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("BACKGROUND", (0, 1), (-1, -1), colors.HexColor("#f8f9fa")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f0f0f0")]),
        ("PADDING", (0, 0), (-1, -1), 8),
    ]))
    story.append(table)
    story.append(Spacer(1, 0.5*cm))

    # Maintenance Plan section
    section_style = ParagraphStyle("section", fontSize=13, fontName="Helvetica-Bold",
                                    textColor=colors.HexColor("#1a1a2e"), spaceAfter=6, spaceBefore=12)
    body_style = ParagraphStyle("body", fontSize=10, leading=16, spaceAfter=6)

    story.append(Paragraph("Maintenance Plan", section_style))
    plan_text = data.get("maintenance_plan", "").replace("\n", "<br/>")
    story.append(Paragraph(plan_text, body_style))

    # Cost Analysis section
    cost = data.get("cost_analysis", {})
    if cost:
        story.append(Paragraph("Cost Analysis", section_style))
        opt_a = cost.get("option_a", {})
        opt_b = cost.get("option_b", {})
        summary = cost.get("decision_summary", {})

        cost_data = [
            ["Decision Option", "Cost Estimate"],
            ["Planned maintenance now", opt_a.get("total_cost", "N/A")],
            ["Expected cost if failure occurs", opt_b.get("expected_cost", "N/A")],
            ["Savings from acting now", summary.get("acting_now_saves", "N/A")],
        ]
        cost_table = Table(cost_data, colWidths=[9*cm, 8*cm])
        cost_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#16a34a")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 10),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f0fdf4")]),
            ("PADDING", (0, 0), (-1, -1), 8),
        ]))
        story.append(cost_table)

    # Footer
    story.append(Spacer(1, 1*cm))
    footer_style = ParagraphStyle("footer", fontSize=8, textColor=colors.grey, alignment=1)
    story.append(Paragraph(
        "Generated by FeMind — Steel Plant Institutional Intelligence | Tata Steel AI Hackathon 2026",
        footer_style
    ))

    doc.build(story)
    return filename
